#spring.application.name=server
server:
  port: 8080

spring:
  mail:
    smtp:
      host: smtp.gmail.com
      port: 587
      username: abdusharipovizzat03@gmail.com
      password: 1234

  datasource:
    url: jdbc:postgresql://localhost:3306/postgres
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: uzbekistan1Uzbekistan2Uzbekistan3
  access-time: 90000
  refresh-time: 604800000

client:
  url: http://localhost:5173